### ISSUE TITLE
Tool is case sensitive to XML tags

### ISSUE THREAD

**Issue by joaomoreno** [davidebbo/WAWSDeploy#10]
I tried this tool with a given publish settings from Azure. It first told me:

```Deployment failed: Expected root node to be 'publishData'```

I opened the file and the tag name was `PublishData`. After changing it to the camelCase format, the tool went on to complain about:

```Deployment failed: Expected first child node to be 'publishProfile'```

**Comment by davidebbo** [comment]
There are two kinds of publish profile files, which is confusing. You need to use the one that gets downloaded from Azure for a specific Web App.

**Comment by joaomoreno** [comment]
Yep, it was exactly that.

Maybe you can add a screenshot to `README.md` showing the link to download the publish profile from a web site.

You could also inform the user that he might be using the wrong type of publish profile if you can detect it. :+1:

**Comment by davidebbo** [comment]
Ok, I added clarification to the readme.
