### ISSUE TITLE
Could WAWSDeploy be used in an existing Azure Web App?

### ISSUE THREAD

**Issue by yooakim** [davidebbo/WAWSDeploy#11]
I'm sorry for making this an issue... it is more of a question. I hope that is ok?

What I am trying to solve is how to take en existing Azure Web App and be able to Deploy this web app to another existing Azure Web App (from TEST -> STAGE for example)

What would be very nice is if one could simply have a Site Extensions (maybe based on WAWSDeploy) that would, given a publishSettings file) Deploy the website to the server given in the publishSettings file.

I'm helping a hosting provider that is running a PaaS services and they can not enforce teir customers to package in a special way. And they do not have access to source. code... 

The partners Deploy to DEV Environments (Web Apps in Azure) and what then needs to be done is move that to Another Web App.

Could WAWSDeploy help? or are there better ways?

/Joakim

**Comment by davidebbo** [comment]
Please take a look at Site Replicator (https://github.com/projectkudu/AzureSiteReplicator), which does something like this. Though note that it's not an official offering.
