### ISSUE TITLE
Source (sitemanifest) and destination (contentPath) are not compatible for the given operation.

### ISSUE THREAD

**Issue by Centine** [davidebbo/WAWSDeploy#12]
I suspect this is not really an WAWSDeploy problem but rather something underlying.  I'm trying to bundle up an console application (which is a web job) and deploy to Azure.

If I build a package (with `msbuild  /t:Package $CSProjFilePath   /p:_DestinationType=AzureWebSite", "/p:SkipInvalidConfigurations=true", "/p:PackageLocation=build.staging\", "/p:PublishProfile=<name of publish profile>"` I get a zip file with our project (a deeply nested zip file) in build.staging\csproj.zip. The zip file is valid (broken zip files seem to be the most common source of the error).

I then run `wawsdeploy .\build.staging\csproj.zip .\my.PublishSettings /d` I always get a `Deployment failed: (14-03-2016 16:34:49) An error occurred when the request was processed on the remote computer.` In the event viewer I can see `Source (sitemanifest) and destination (contentPath) are not compatible for the given operation.`. 

If I try to create a simple zip-file with just a text file instead and do `wawsdeploy .\my.zip .\my.PublishSettings /d`, it works fine. I suspect operator error, but can't figure out where to start looking.

**Comment by davidebbo** [comment]
One thing you might try is whether you are able to deploy that package directly using msdeploy.exe. msdeploy.exe has much more flexibility than wawsdeploy (which is also why it's so hard to use!), and it may be that this kind of package is not covered by wawsdeploy.exe.

@shobak101 might have input on this as well

**Comment by Centine** [comment]
Thanks for the feedback! We've managed to progress on the issue and not surprisingly, the issue was not WAWSDeploy. Thanks for making it available.

Just to leave some feedback for others that might hit the same package generation issue and see this error: After some experimentation, somewhere in the interaction with msbuild and the mystery files that guides how the package is formed, we end up with a zip package file with some parameter files in the root, which msdeploy disagrees with. Creating a simple zip file that matches the directory structure on the destination (matching the directory structure for web jobs here) and a valid publish profile makes WAWSDeploy work beautifully.

**Comment by shobak101** [comment]
WAWSDeploy only uses ContentPath provider which at the end only copies files over, when MSBuild creates the package it adds some more information to the package that might not be needed in your case.
