### ISSUE TITLE
Enable Rules

### ISSUE THREAD

**Issue by joaomello** [davidebbo/WAWSDeploy#14]
Hi, very nice project!
I'm using with dotnet core, to publish on azure. I call

``` bash
dotnet publish -c release
wawsdeploy .\bin\release\net452\win7-x64\publish app.PublishSettings
```

But I'm getting this error:

> Deployment failed: Web Deploy cannot modify the file 'app.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.

So... here: https://github.com/davidebbo/WAWSDeploy/blob/master/WAWSDeploy/WebDeployHelper.cs#L86

I did...

``` C#
DeploymentRule rule;
Microsoft.Web.Deployment.DeploymentSyncOptions.GetAvailableRules().TryGetValue("AppOffline", out rule);
syncOptions.Rules.Add(rule);
```

Would be bad idea if add an extra parameter to add rules?

**Comment by davidebbo** [comment]
Yes, sounds like a good idea!

However, I'm not sure that AppOffline is even honored for .net core apps. Did you check whether manually creating this file (via KuduConsole) makes things work?

**Comment by joaomello** [comment]
I don't how is the "best way" to publish asp.net core on azure. I just saw that VS creates a profile with this rule. Because without that, give an error. I'll create a kudu, like you said to see.

**Comment by moozzyk** [comment]
app_offline.html is an Asp.NET Core Module feature. I described it a little bit in my post https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/. It is used by default by WebDeploy in VS when publishing an ASP.NET Core apps to Antares.

**Comment by davidebbo** [comment]
Ok, so it sounds like it would work. @joaomello feel free to send PR!

**Comment by Ackara** [comment]
Hi fellas I ran into this same issue so I created a PR #17  to add the AppOffline parameter, please take a look.
