### ISSUE TITLE
Thow exception on errors

### ISSUE THREAD

**Issue by IvanovOleg** [davidebbo/WAWSDeploy#15]
Wawsdeploy thows a regular output message on deployment errors:

**Deployment failed: Из-за ошибки подключения веб-развертывания к серверу подключение было прервано. При повторении ошибки обратитесь к администратору сервера.  Дополнительные сведения: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.**

Deployment has been terminated because of a server connection error.

I can't catch this error via try-catch because it is not an exception. Can you fix it?

**Comment by davidebbo** [comment]
Does it work if you use msdeploy.exe directly, or publish from VS? If not, then the issue is not directly related to wawsdeploy.

**Comment by davidebbo** [comment]
Ok, maybe I misread the issue. You're not complaining that it fails, but that it doesn't throw? Though I'm confused, as wawsdeploy is a command line tool and not a library. Are you referring to the %errorlevel% being wrong?

**Comment by IvanovOleg** [comment]
Yes, it doesn't matter for  me what happened, the only thing I need is to get an exception when it fails. It will allow my Jenkins job to set a proper build status.

```
try {
    wawsdeploy ...
} catch {
    $lastExitCode = 1
}
```
This code doesn't work because there are no exceptions.

**Comment by davidebbo** [comment]
To be clear, command line tools cannot 'throw'. What they do is return an error code, where 0 means success and non-zero means error. But I checked wawsdeploy already does this correctly, and returns 1 in any error happens. See the code [here](https://github.com/davidebbo/WAWSDeploy/blob/876f42c9a13401642cf5f32df81e0992ad916d6f/WAWSDeploy/Program.cs#L57-L61). I don't think there is anything else it can do than return an error code.

**Comment by IvanovOleg** [comment]
It looks like you should change:
`Environment.ExitCode = 1;`
to:
`Environment.Exit(1);`

**Comment by davidebbo** [comment]
The current code is correct. Just try running a command that returns an error, and then look at the value of %errorlevel%, which will be 1.

**Comment by IvanovOleg** [comment]
I am using a powershell script for the deployment and there is no %errorlevel%. If I run wawsdeploy with a wrong arguments it returns an exception, but it doesn't react on **ERROR_CONNECTION_TERMINATED**. It returns a plain text that can't be processed via try-catch

**Comment by davidebbo** [comment]
I think you're misunderstanding how Console apps return errors. Try writing a trivial test Console app that returns an error in the way that you think is correct, test it in your scenario, and if it works differently from wawsdeploy, please share code on GitHub.

**Comment by davidebbo** [comment]
Note that is PS, errorlevel equivalent is `$LASTEXITCODE`. You just need to write code that.

**Comment by sadomovalex** [comment]
last comment helped. In PowerShell I checked that upload was successful like that:
```powershell
if ($LASTEXITCODE -ne 0) {
    throw "WAWSDeploy failed to upload file"
}
```
