### ISSUE TITLE
Building solution: Args cannot be found

### ISSUE THREAD

**Issue by DoubleCouponDay** [davidebbo/WAWSDeploy#18]
There is a dependency in the project which is not included. DeploymentArgs.cs requires a location for ArgsMemberSwitch attribute.

**Comment by davidebbo** [comment]
Can you please provide more details? What exactly are you doing, and what are you seeing?

**Comment by DoubleCouponDay** [comment]
Sure here are some screenshots of the compilation errors.

![Uploading error 1.png…]()
![Uploading error 2.png…]()

**Comment by davidebbo** [comment]
That's not really a compilation error, but may just mean packages are not yet restored. Try building from VS, and if you get errors, please paste the relevant build output (as text, not screenshot). Also, try building from command line. It works either way for me.

**Comment by DoubleCouponDay** [comment]
The problem was the Args 1.1.1 package is not downloaded until the solution is built.
