### ISSUE TITLE
Continue if files are locked when trying to delete

### ISSUE THREAD

**Issue by SteveALee** [davidebbo/WAWSDeploy#19]
Am using with Azure Functions and if a function is open for viewing in the portal then I sometime get an "locked" error. The same may happen with replacing files I guess.

Would it be possible to just continue after such an error? Perhaps you do and it's just the error return giving this impression?

**Comment by davidebbo** [comment]
If msdeploy has such option, it should be easy to add support for it in wawsdeploy. But I'm not sure if it does.

See also https://github.com/Azure/azure-webjobs-sdk-script/issues/1521.

**Comment by SteveALee** [comment]
Useful. Thanks. Though it would require some fiddling to use it. Or a functions specific option to WSASDeply.

**Comment by Ackara** [comment]
Try using the /AppOffline arg it will stop the app before deploying (thus releasing all locks)

WAWSDeploy c:\somefolder mysite.PublishSettings /d /AppOffline

**Comment by davidebbo** [comment]
@Ackara unfortunately, that won't work for Functions, because it doesn't support App_Offline. See https://github.com/Azure/azure-webjobs-sdk-script/issues/1521

**Comment by chaami** [comment]
The support of App_Offline in Azure function has been merged in August 2018.
So I think the `/AppOffline` should work...
Could you by chance confirm and close ?

**Comment by chaami** [comment]
Add a comment if the issue needs to be reopened.
