### ISSUE TITLE
Parameter entry 'IIS Web Application Name/1' could not be applied anywhere

### ISSUE THREAD

**Issue by jaredcnance** [davidebbo/WAWSDeploy#21]
### Problem

I want to separate the build and deployment steps of my azure app services. I can create the artifacts to be published with msbuild:

```
msbuild /p:Configuration=Release /p:DeployOnBuild=true;DeployTarget=Package
```

Then I would like to publish those artifacts and I'm trying to do this with WAWSDeploy:

```
 WAWSDeploy MyApp.zip dev-myApp.publishSettings /w /v
```

which throws the following error

```
Starting deployment...
Using ID 'd909b7b0-e2b9-4834-8571-1a81c0e19883' for connections to the remote server.
Pre-authenticating to remote agent URL '...' as '$...'.
Performing synchronization pass #1.
Pre-authenticating to remote agent URL '...' as '$...'.
Parameter entry 'IIS Web Application Name/1' could not be applied anywhere.
Parameter entry 'IIS Web Application Name/2' could not be applied anywhere.
Received response from agent (HTTP status 'OK').
Deployment failed: (8/25/2017 11:17:27 AM) An error occurred when the request was processed on the remote computer.
```

It seems that I need to be able to pass this flag into msdeploy, but I don't think this is possible using the tool.

```
-setParam:name="IIS Web Application Name",value="dev-myApp"
```

**Comment by davidebbo** [comment]
Right wawsdeploy is mostly about copying files, and doesn't support some of the more advanced msdeploy semantics. You'll need to drop back to msdeploy.exe.
